### PR TITLE
minor tweaks for grails 2.4 compatibility

### PR DESCRIPTION
**Pull request by Omasiri**

### CODE REVIEW

**Comment by scryan7371** [comment]
Does this allow for support for Hibernate 4.x  How do we get this released to the plugin repository?  I would love to use 2.4 and 4.x but need this plugin to be up to snuff and available to all my projects.  If I can help in any way please let me know

Scott Ryan
Soaring Eagle L.L.C.

**Comment by Omasiri** [comment]
This does not allow for use with Hibernate 4.x. yet. I worked on it and so far it passed all unit tests :) 
To make this plugin fully compatible with hibernate 4.x  requires modifications to hawk-eventing and hibernate-hijacker plugins ( multitenant-single-db depends on both). I have created modified versions of those plugins to avoid tampering with hibernate 3.x compatible plugins. You may find the modified versions by visiting https://github.com/Omasiri/hawk-eventing-h4 and https://github.com/Omasiri/hibernate-hijacker-h4  ( could be transferred )

The remaining task is to get this plugin to pass all integration tests. Please take a look at the plugins.

**Comment by sronderos** [comment]
Hi Omasiri,  

Why did you close the request? I haven't had time to look into the proposed changes, but I will try to do so now.  Do you know of any changes that you've made that will cause the plugin to fail on previous versions?

-Steve

**Comment by sronderos** [comment]
Hi Omasiri,

First off, thanks for all of your contributions!  It really looks like you've put a lot of work into them.

I tried to look through your new h4 plugins.  Unfortunately, since they don't have a common base with the existing plugins I had a hard time seeing the changes.  Would you mind creating pull requests against each of those projects instead of creating new projects?  That would make it much easier to see the changes you've made.  At this point I think that it would be best to upgrade all 3 plugins to only support hibernate 4.  Anyone that wishes to stay on Hibernate 3 will have to continue to use the existing version of the plugin.

Do you think that you would be able to modify this PR to simply support Grails 2.4.x so that I can accept that PR and then I can help tackle the Hibernate 4 changes?

Thanks,
Steve

**Comment by Omasiri** [comment]
Hello Steve,
I will modify and send the PR for Grails 2.4.x as requested. I would like to make a PR against the other dependencies ( hawk-eventing and hibernate-hijacker) but I have not been able to find both of them on github yet. Please send me their respective links so I can send the PR as requested.

Thank you.
Omasiri

**Comment by sronderos** [comment]
https://github.com/multi-tenant/grails-hawk-eventing
https://github.com/multi-tenant/grails-hibernate-hijacker

**Comment by Omasiri** [comment]
Hello Steve, 
Thanks for the links. I have reverted the multi-tenant-single-db back to 2.4.x compatibility. Please take a look.

Thanks
Omasiri

**Comment by kimble** [comment]
I've not been doing any serious Grails development for a few years now, but I'm very happy to see that people are still working on this. 

Isn't there better built in support (or a plugin) for events in Grails now? It would probably not be a bad idea to swap Hawk Eventing for something that's supported by the community..

**Comment by Omasiri** [comment]
Hello Kim,
Please take a look at http://grailsrocks.github.io/grails-platform-core/guide/events.html. 

-----Original Message-----

**Comment by kimble** [comment]
That is probably the one I was thinking about. If that is maintained and has gained some adoption it might be worth killing off hawk eventing.

**Comment by sronderos** [comment]
Omasiri, I was looking over your changes and I was concerned about the changes to the tests.  It looks like something in the update to Spring has caused the tenant scoped service feature to break.  I've made some changes here: https://github.com/sronderos/grails-multi-tenant-single-db/tree/Omasiri-master

Please take a look.  I won't be available for a few days, but I believe that we should at least try to keep the tenant scoped bean feature.  It was marked as experimental, but we have no way of knowing how much use it gets.  @kimble, @scryan7371 do you guys use that feature at all?

**Comment by Omasiri** [comment]
Hello Steve,
You are right. I think it will be good to keep features people use. I tried to find a way around and removed the test for scoped services after reading http://grails.org/doc/2.4.2/ref/Services/scope.html and http://grails.org/doc/2.4.2/guide/single.html#scopedServices. Please let me know what you think and how we can make it work.

Thanks

**Comment by sronderos** [comment]
Hi Omasiri,

I agree with the documentation that storing state within a service is an anti-pattern, but it is none the less still supported within standard grails functionality.  You can still create a session scoped service and store state in it.  Again, I don't think that I would do this, but there could be valid use cases to do so.  This is more of a question about removing functionality.  Perhaps ask the mailing list if anyone is using this feature?  I'm always nervous about removing functionality, but if the effort to maintain the feature is disproportional to the value of the feature, then we should make the hard decision to kill the feature.  I'd really be interested to see what the community and especially Kim and Scott think.

-Steve

**Comment by kimble** [comment]
I have to admit that the tenant scope feature was something I looked into more because I was curious about how scopes were implemented in Spring then anything else :-)  I have no idea whether the current implementation ever worked well enough to be used in production. 

It's flagged as experimental in the documentation so I'd say just remove it to ease maintenance of this project. If someone really does use it they can always pull the source code into their application. Just my two cents.

**Comment by scryan7371** [comment]
I have never used the service based tenancy as it seems to a bad idea.  Our
services never store state and are reentrant.   In order to support the
performance and statelessness we desire we have always found other ways to
accomplish this.  I would encourage us to remove that capability as it
encourages bad practices.  Also as more and more platforms include multi
tenancy in their offers I hope some day we can remove this plugin from
those environments.  The future multitenant environments tend to be more
data based rather than service based to the transition would be difficult.

I also like the idea of adopting the new eventing layer in favor of Hawk as
it hopefully will move forward with current versions and also will be more
general purpose and be tuned and debugged by a wider audience.   I am
excited about getting a 2.4 version out as well as a version that works
with the latest hibernate as I would really like to move onto it for many
reasons.

Let me know how i can assist.

Scott RYan

Scott Ryan
President/CTO
Soaring Eagle L.L.C.
Highlands Ranch, Co. 80130
(303) 263-3044
scott@theryansplace.com
www.soaringeagleco.com

**Comment by sronderos** [comment]
Hey Scott,

Thanks for replying. I think we are all in agreement. Let's go ahead and remove the services features from the plugin.  I'll create an issue to track that separately. Additionally I'll make an issue to switch to the [Grails Platform Events](http://grailsrocks.github.io/grails-platform-core/guide/events.html).

I think that we will need to finish both of those tasks before the plugin can move to Hibernate 4, and unfortunately I don't think that there is much value in releasing a version of the plugin that is compatible with Grails 2.4 without Hibernate 4 compatibility.

As for helping out, Scott if you want to take a stab at either of the new tickets I'll do my best to stay on top of any pull requests.

Let me know what you guys think.
Steve

**Comment by aberbenni** [comment]
Any news about this pull request?

**Comment by bluesliverx** [comment]
I'm also wondering about this support - is there any work remaining for grails 2.4 compatibility?  I'm willing to help out if needed.  I don't think I need hibernate4 compat yet, but at least grails 2.4 would be nice.

**Comment by scryan7371** [comment]
I would love to get it converted.  This is the last piece we need before we can move to 2.4 and Hibernate 4.  Lets chat among the team and put a plan together to get it converted.  The first step is to get all the tests running under the latest version of 2.3.X and make sure we have pretty good coverage.  Then we need to convert from Hawk Eventing to the Grails Eventing via Spring then we can convert the plugin.  We also would like to drop the support for Spring Beans being multi tenant.   

If everyone can send me an email I will set up a conference call and we can divide up the work and cross check each other.  It is key to do this right so we don’t open any security holes.  I think if we put a plan together a few of us can bang it out in a week and with the holidays we might get more free time to do this than normal.

Let me know your thoughts

Scott Ryan
Soaring Eagle L.L.C.
scott@theryansplace.com

Contact Me:  LinkedIn http://www.linkedin.com/in/scottdryan Facebook http://www.facebook.com/scryan7371
Twitter http://twitter.com/scryan7371

**Comment by Omasiri** [comment]
Hello Scott,

Here's my email address: omasiri@novadge.com.

Thank you.

On Sat, Dec 6, 2014 at 5:57 PM, Scott Ryan notifications@github.com wrote:

> I would love to get it converted. This is the last piece we need before we
> can move to 2.4 and Hibernate 4. Lets chat among the team and put a plan
> together to get it converted. The first step is to get all the tests
> running under the latest version of 2.3.X and make sure we have pretty good
> coverage. Then we need to convert from Hawk Eventing to the Grails Eventing
> via Spring then we can convert the plugin. We also would like to drop the
> support for Spring Beans being multi tenant.
> 
> If everyone can send me an email I will set up a conference call and we
> can divide up the work and cross check each other. It is key to do this
> right so we don't open any security holes. I think if we put a plan
> together a few of us can bang it out in a week and with the holidays we
> might get more free time to do this than normal.
> 
> Let me know your thoughts
> 
> Scott Ryan
> Soaring Eagle L.L.C.
> scott@theryansplace.com
> 
> Contact Me: LinkedIn http://www.linkedin.com/in/scottdryan Facebook <
> http://www.facebook.com/scryan7371>
> Twitter http://twitter.com/scryan7371
> 
> > On Dec 6, 2014, at 9:49 AM, Brian Saville notifications@github.com
> > wrote:
> > 
> > I'm also wondering about this support - is there any work remaining for
> > grails 2.4 compatibility? I'm willing to help out if needed. I don't think
> > I need hibernate4 compat yet, but at least grails 2.4 would be nice.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub <
> > https://github.com/multi-tenant/grails-multi-tenant-single-db/pull/38#issuecomment-65904885>.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/multi-tenant/grails-multi-tenant-single-db/pull/38#issuecomment-65905155
> .

## 

Omasirichukwu J. Udeinya,
Computer Systems Analyst,
Novadge.
Telephone: 234-703- 763-5200

**Comment by marcoz-tsn** [comment]
I wish to thank you all for this upgrade effort! ..and wonder if there are news about an RC of the new plugin... I know that "no news, good news" ;), but we (many people and I, I'm sure!) wish to test it in Hibernate4!

PS: obviously I'll be glad to help, even though I'm not between the most skilled volounteers, here.. anyway, let me know.

**Comment by Omasiri** [comment]
Hey Scott,
I was wondering how I can assist with the upgrade effort following our decision to replace hawk eventing in the multitenant single db plugin.  Please let me know. Thanks @scryan7371 @kimble @sronderos

**Comment by scryan7371** [comment]
I am really wanting it to happen so i can get to 3.0 and Hibernate 4.0

Is there any way we can release what we have as a release so i can use it to migrate to 2.5 and see how it works out.

**Comment by Omasiri** [comment]
The plugin works with grails 2.4.4 and should work with grails 2.5 ( with hibernate 3 ). Compatibility with Hibernate 4 and a switch away from hawkeventing will make it straightforward to upgrade to grails 3.0. 
Let us see what you have and maybe think of a way forward :)

**Comment by Omasiri** [comment]
@scryan7371 , @kimble , @sronderos : I think this plugin will work with grails 3.1.1 now ... with hibernate3 :)   I have upgraded hawk-eventing and hibernate-hijacker to go with it for the mean time.
I need help with this because I don't know the inner workings of the plugin as well as you guys.
The unit tests passed but the integration tests......

**Pull request closed without merging**
