### PR TITLE
Unable to delete when using withoutTenantRestriction

### PR DESCRIPTION
**Pull request by sronderos**
I happened upon this issue during my development.  Currently the hibernate filter prevents deletes from executing when the current tenant id is null.  It is my understanding that having no current tenant id should allow unrestricted access to view, update or delete assets.

Please let me know if the delete functionality was not intended to work with the "withoutTenantRestriction" feature.

### CODE REVIEW

**Comment by kimble** [comment]
That sounds about right, but it's a bit hard to see what has changed in the patch..

**Comment by sronderos** [comment]
Oh, I didn't notice how awful the merge was. I expect it has something to do with line endings. I'll see if I can clean it up to make the patch easier to read.

**Comment by sronderos** [comment]
Ok, those files should be easier to read now.  Somehow I also had some bad line endings in documentation that I had written the other day, and apparently the license had CRLF in it as well.  Sorry for the clutter in the diff view, but it should be easier to see the changes I made for the delete functionality.

**Comment by kimble** [comment]
Looks good to me, I've never really used the "no tenant back door" which is probably why I've never experienced any issues with it.

**Pull request merged**
